version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    ports:
      - "5432:5432"
