# Generated by Django 5.2.4 on 2025-07-21 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditentry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
