# Generated by Django 5.2.4 on 2025-07-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_timestamp_creditentry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditentry',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
